
services:

  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    
  spring-service:
    hostname: spring-service
    depends_on:
      - redis
    build: .
    ports:
      - "8080:8080"
    environment:   
      - STORAGE_TYPE=redis
      - REDIS_URL=redis:6379