spring:
  application:
    name: simpleAnagramBackend

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      
server:
  port: ${LISTEN_PORT:8080}
  
redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT::6379}
