spring:
  application:
    name: simpleAnagramBackend

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      
server:
  port: ${SERVER_PORT:8080}
  
redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

haselcast:
  max-int-retry: ${HAZELCAST_MAX_INIT_RETRY:10}
  node:
    ips: ${HAZELCAST_NODE_IPS:hazelcast-node1:5701,hazelcast-node2:5702}
  cluster:
    name:  ${HAZELCAST_CLUSTER_NAME:hazelcast-cluster}
  instance: ${HAZELCAST_INSTANCE:anagram}
 