openapi: 3.0.2
info:
  description: This simple app checks and finds anagrams.
  title: Simple Anagram Backend
  version: 1.0.0
servers:
- url: https://localhost/v1
paths:
  /health:
    description: "Endpoint for health Return 200 if service is healty, an error from\
      \ the 5XX range otherwise."
    get:
      operationId: health
      responses:
        "200":
          description: Service is Up and running
        "5XX":
          description: Unexpected error
  /info:
    description: "Endpoint for info Returns basic application information :see title,\
      \ version and description"
    get:
      operationId: infoGet
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Service is Up and running
        "5XX":
          description: Unexpected error
  /anagrams:
    post:
      description: This endpoint takes two strings and returns true if they are anagrams.
        The strings are preserved within a single run.
      operationId: anagramsPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/anagramProcessRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/anagramProcessResponse'
          description: Successful
        "400":
          description: Bad request if one of the required fields is missing
      summary: This endpoint takes two strings and checks if theyare anagrams of each
        other
  /anagrams/find:
    post:
      description: This endpoint takes a strings and returns all anagrams that were
        previously reuested.
      operationId: anagramsFind
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/anagramFindRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/anagramFindResponse'
          description: Successful
        "400":
          description: Bad request if one of the required fields is missing
      summary: Get all in memmory stored anagrams for a provided text. POST request
        for lenght and security resons.
components:
  schemas:
    anagramFindRequest:
      description: anagramFindRequest
      example:
        text: Hello
      properties:
        text:
          type: string
      required:
      - text
      title: anagramFindRequest
      type: object
    anagramFindResponse:
      description: anagramFindResponse
      example:
        string: Hello
        anagrams:
        - olleH
        - Holle
      properties:
        text:
          type: string
        anagrams:
          items:
            type: string
          type: array
      required:
      - anagrams
      - text
      title: anagramFindResponse
      type: object
    anagramProcessRequest:
      description: anagramProcessRequest
      example:
        textA: Hello
        textB: World
      properties:
        textA:
          type: string
        textB:
          type: string
      required:
      - textA
      - textB
      title: anagramProcessRequest
      type: object
    anagramProcessResponse:
      description: anagramProcessResponse
      example:
        stringA: Hello
        stringB: World
        result: false
        message: The strings 'Hello' and 'World' are not anagrams
      properties:
        textA:
          type: string
        textB:
          type: string
        result:
          type: boolean
        message:
          type: string
      required:
      - message
      - result
      - textA
      - textB
      title: anagramProcessResponse
      type: object
